services:
  mcpdev:
    build:
      context: ..
      dockerfile: docker-dev/Dockerfile
    volumes:
      - ../:/workspace:cached
      - ~/.ssh:/root/.ssh:cached
      - ~/gitconfig:/root/gitconfig:cached
    working_dir: /workspace
    entrypoint: ["tail", "-f", "/dev/null"]
    ports:
      - "5678:5678" # debugpy remote debugging
      - "33001-33010:33001-33010" # MCP ports SSE ports
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    # For Chinese users
    environment:
      TZ: Asia/Shanghai
      LANG: zh_CN.UTF-8
      LANGUAGE: zh_CN:zh
      LC_ALL: zh_CN.UTF-8
      no_proxy: "localhost,127.0.0.1"
      NO_PROXY: "localhost,127.0.0.1"
      # EXTERNAL_HOST: "your-host-ip-or-domain"
      EXTERNAL_HOST: "host.docker.internal"
      # Explicitly set the real host IP for external client access
      # Replace with your actual host machine IP on the network
      REAL_HOST_IP: "192.168.1.8"
      
    # labels:
    #   devcontainer.metadata: '{"customizations": {"vscode": {"remote.containers.mountWslDistro": false}}}'
